In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
% matplotlib inline
# Always make it pretty.
plt.style.use('ggplot')

In [72]:
df = pd.read_csv('cleaned_data.csv')

In [73]:
df.head(10)

,price,security_deposit,cleaning_fee,beds,host_response_time,host_is_superhost,neighbourhood_group_cleansed,latitude,longitude,room_type,...,minimum_nights,availability_90,review_scores_rating,reviews_per_month,review_scores_cleanliness,review_scores_checkin,review_scores_location,review_scores_value,cancellation_policy,host_response_rate
0,45,150,50,1,0,0,Queens,40.754444,-73.895933,Private room,...,1,0,90,0.42,8,10,10,10,1,100
1,95,150,50,1,4,1,Manhattan,40.785097,-73.942337,Private room,...,2,24,93,2.33,9,10,8,9,2,100
2,60,150,30,1,2,1,Brooklyn,40.709891,-73.957495,Entire home/apt,...,6,0,100,1.10,10,10,10,10,2,100
3,70,150,20,1,2,0,Manhattan,40.850388,-73.938551,Private room,...,2,30,89,1.00,10,9,9,9,1,100
4,104,150,60,1,2,0,Manhattan,40.766609,-73.968214,Entire home/apt,...,12,46,87,0.17,9,10,10,10,2,60
5,90,150,50,1,0,0,Brooklyn,40.675753,-73.950032,Entire home/apt,...,2,0,100,0.43,10,10,10,10,1,100
6,374,250,200,5,0,0,Manhattan,40.778486,-73.985265,Entire home/apt,...,30,87,95,0.54,9,10,10,9,3,100
7,100,100,30,3,0,0,Manhattan,40.831359,-73.948430,Entire home/apt,...,4,0,95,0.21,10,9,8,9,1,100
8,60,100,20,2,4,0,Bronx,40.869173,-73.894646,Private room,...,3,82,93,3.03,9,10,9,9,3,100
9,175,0,100,1,0,0,Manhattan,40.720334,-74.000030,Entire home/apt,...,1,3,100,0.48,10,10,10,10,3,100

In [69]:
response_rate = df['host_response_rate']

In [71]:
rates = list(response_rate)
print(type(rates[0]))

<class 'int'>

In [58]:
new_rate = []
for rate in rates:
    if type(rate) == str:
        rate_list = list(rate)[:-1]
        rate_perc = 0
        for i in range(len(rate_list)):
            rate_perc += int(rate_list[i])*(10**(len(rate_list)-i-1))
        new_rate.append(rate_perc)
    if type(rate) == float:
        new_rate.append(rate)

In [59]:
df['host_response_rate'] = pd.DataFrame(new_rate)

In [60]:
df.head(10)

,price,security_deposit,cleaning_fee,beds,host_response_time,host_is_superhost,neighbourhood_group_cleansed,latitude,longitude,room_type,...,minimum_nights,availability_90,review_scores_rating,reviews_per_month,review_scores_cleanliness,review_scores_checkin,review_scores_location,review_scores_value,cancellation_policy,host_response_rate
0,45,150,50,1,0,0,Queens,40.754444,-73.895933,Private room,...,1,0,90,0.42,8,10,10,10,1,NaN
1,95,150,50,1,4,1,Manhattan,40.785097,-73.942337,Private room,...,2,24,93,2.33,9,10,8,9,2,100.0
2,60,150,30,1,2,1,Brooklyn,40.709891,-73.957495,Entire home/apt,...,6,0,100,1.10,10,10,10,10,2,100.0
3,70,150,20,1,2,0,Manhattan,40.850388,-73.938551,Private room,...,2,30,89,1.00,10,9,9,9,1,100.0
4,104,150,60,1,2,0,Manhattan,40.766609,-73.968214,Entire home/apt,...,12,46,87,0.17,9,10,10,10,2,60.0
5,90,150,50,1,0,0,Brooklyn,40.675753,-73.950032,Entire home/apt,...,2,0,100,0.43,10,10,10,10,1,NaN
6,374,250,200,5,0,0,Manhattan,40.778486,-73.985265,Entire home/apt,...,30,87,95,0.54,9,10,10,9,3,NaN
7,100,100,30,3,0,0,Manhattan,40.831359,-73.948430,Entire home/apt,...,4,0,95,0.21,10,9,8,9,1,NaN
8,60,100,20,2,4,0,Bronx,40.869173,-73.894646,Private room,...,3,82,93,3.03,9,10,9,9,3,100.0
9,175,0,100,1,0,0,Manhattan,40.720334,-74.000030,Entire home/apt,...,1,3,100,0.48,10,10,10,10,3,NaN

In [61]:
df.to_csv('cleaned_data.csv',index=False,sep=',')